theme: jekyll-theme-cayman
title: Manuel Herrera
name: Portfolio
description: Full-stack/Backend software developer
show_downloads: true
ghlink: https://github.com/manuelmhs
lilink: https://www.linkedin.com/in/...
cvlink: /assets/manuel-herrera-cv.pdf
