theme: jekyll-theme-cayman
title: Manuel Herrera
description: Full-stack/Backend software developer
show_downloads: true
ghlink: https://github.com/manuelmhs
lilink: https://www.linkedin.com/in/manuelmhs1104/
cvlink: /assets/manuel-herrera-cv.pdf
